YouDeliberate/Models/Entity/comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouDeliberate.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int commentID { get; set; }
        public string content { get; set; }
        public System.DateTime timestamp { get; set; }
        public int narrativeID { get; set; }
        public string hash { get; set; }
        public string flagged { get; set; }
    
        public virtual narrative narrative { get; set; }
        public virtual comment comment1 { get; set; }
        public virtual ICollection<comment> comments { get; set; }
    }
}

YouDeliberate/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using YouDeliberate.Models.DAO;
using YouDeliberate.Models.Entity;
using YouDeliberate.Models.Services;
using System.Security.Cryptography;
using SystemWrapper.IO;

namespace YouDeliberate.Controllers
{
    public class AdminController : Controller
    {
        private ServiceRegistry registry;

        public AdminController()
        {
            registry = new ServiceRegistry();
        }

        public AdminController(IUploadService UploadService, IFileService FileService, 
                               INarrativeService NarrativeService, IAuthService AuthService)
        {
            registry = new ServiceRegistry();
            registry.UploadService = UploadService;
            registry.FileService = FileService;
            registry.NarrativeService = NarrativeService;
            registry.AuthService = AuthService;
        }

        public ActionResult Index()
        {
            IAuthService authService = registry.AuthService;
            return View(authService.VerifyLogin("Upload", Session));
        }

        public ActionResult Comments()
        {
            IAuthService authService = registry.AuthService;
            return View(authService.VerifyLogin("Comments", Session));
        }

        public ActionResult Config()
        {
            IAuthService authService = registry.AuthService;
            if (authService.VerifyLogin("Config", Session) != "Config")
            {
                return View("Index");
            }

            IAdminService adminService = registry.AdminService;
            List<administrator> adminList = adminService.GetAllAdmins();
            return View(adminList);
        }

        [HttpGet]
        public ActionResult AddAdmin(string user, string pass, string email)
        {
            administrator admin = new administrator();
            AdminService adminService = new AdminService();
            admin.username = user;
            admin.password = pass;
            admin.email = email;
            adminService.selectOption(admin,"add");
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ModAdmin(string user, string pass, string email)
        {
            administrator admin = new administrator();
            AdminService adminService = new AdminService();
            admin.username = user;
            admin.password = pass;
            admin.email = email;
            adminService.selectOption(admin,"mod");
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DelAdmin(int id)
        {
            AdminService adminService = new AdminService();
            adminService.delId = id;
            adminService.selectOption(null,"del");
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetComments(int start, int end)
        {
            List<string> result = new List<string>();
            INarrativeService narrativeService = registry.NarrativeService;
            result = narrativeService.GetComments(start,end);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DelComment(int id)
        {
            INarrativeService narrativeService = registry.NarrativeService;
            return Json(narrativeService.DelComment(id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetNrComments()
        {
            int result = 0;
            INarrativeService narrativeService = registry.NarrativeService;
            result = narrativeService.GetNrComments();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult NewTopic(FormCollection form, HttpPostedFileBase uploadFile)
        {
            ITopicService topicService = registry.TopicService;
            topic topic = new topic();
            topic.content = form["topic"];
            topic.subcontent = form["subtopic"];

            HttpFileCollection UploadedFile = System.Web.HttpContext.Current.Request.Files;
            HttpPostedFile bgImg = UploadedFile[0];
            HttpPostedFile enVid= UploadedFile[1];
            HttpPostedFile frVid = UploadedFile[2];
            if (bgImg.ContentLength > 0 || enVid.ContentLength > 0 || frVid.ContentLength > 0 || topic != null)
            {
                topicService.AddTopic(bgImg, enVid, frVid, topic);
            }

            return View("Config");
        }


        public ActionResult Logout()
        {
            IAuthService authService = registry.AuthService;
            authService.Logout(Session);
            return View("Index");
        }

        public ActionResult Upload()
        {
            IAuthService authService = registry.AuthService;
            return View(authService.VerifyLogin("Upload", Session));
        }

        [ActionName("Login")]
        [AcceptVerbs("Post")]
        public ActionResult Login(FormCollection form)
        {
            IAuthService authService = registry.AuthService;
            if (authService.Login(form["user"], form["password"], Session))
            {
                return View("Upload");
            }

            return View("Index");
        }

        public ActionResult Metrics()
        {
            IAuthService authService = registry.AuthService;
            INarrativeService narrativeService = registry.NarrativeService;
            //ViewData["Dictionary"] = GetNonAnalyticMetrics();
            ViewData["views"] = narrativeService.GetTotalViews();
            ViewData["comments"] = narrativeService.GetTotalComments();
            ViewData["flagged"] = narrativeService.GetTotalFlagged();
            return View(authService.VerifyLogin("Metrics", Session));
        }

        public ActionResult List(string f, int start = 0, int end = 0)
        {
            IAuthService authService = registry.AuthService;
            INarrativeService narrativeService = registry.NarrativeService;
            if (authService.VerifyLogin("List", Session) != "List")
            {
                return View("Index");
            }

            if (f != null)
            {
                if (f == "flagged")
                    return View(narrativeService.GetNarratives(flagged: true));
                else if (f == "nc")
                    return View(narrativeService.GetNarratives(uncategorized: true));
            }

            return View(narrativeService.GetNarratives(start, end));
        }

        public ActionResult GetFlags(int id)
        {
            IAuthService authService = registry.AuthService;
            INarrativeService narrativeService = registry.NarrativeService;
            if (authService.VerifyLogin("List", Session) != "List")
            {
                return View("Index");
            }

            return Json(narrativeService.GetFlags(id), JsonRequestBehavior.AllowGet);
        }

        public ActionResult SetCategory(FormCollection form)
        {
            INarrativeService narrativeService = registry.NarrativeService;

            try
            {
                narrative n = new narrative();
                n.narrativeID = Int32.Parse(form["id"]);
                n.categoryID = Int32.Parse(form["form"]);

                List<Expression<Func<narrative, object>>> modified = new List<Expression<Func<narrative, object>>>();
                modified.Add(narr => narr.categoryID);

                narrativeService.Save(n, modified);
            }
            catch (Exception) {}

            return View("List", narrativeService.GetNarratives());
        }

        public ActionResult SetViewable(FormCollection form)
        {
            INarrativeService narrativeService = registry.NarrativeService;

            try
            {
                narrative n = new narrative();
                n.narrativeID = Int32.Parse(form["id"]);

                if (form["form"] == null)
                    n.userViewable = false;
                else
                    n.userViewable = true;

                List<Expression<Func<narrative, object>>> modified = new List<Expression<Func<narrative, object>>>();
                modified.Add(narr => narr.userViewable);

                narrativeService.Save(n, modified);
            }
            catch (Exception) {}

            return View("List", narrativeService.GetNarratives());
        }

        [HttpGet]
        public ActionResult ChangeTopic(int id)
        {
            ITopicService topicService = registry.TopicService;
            topicService.ChangeOnlineTopic(id);
            return View("Config");
        }

        [HttpGet]
        public ActionResult GetTopicList()
        {
            ITopicService topicService = registry.TopicService;
            List<string> topList = topicService.GetListAllTopics();
            return Json(topList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetAdminList()
        {
            IAdminService adminService = registry.AdminService;
            List<string> adminList = adminService.GetAllAdminsString();
            return Json(adminList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, FormCollection form)
        {
            IFileService fileService = registry.FileService;
            IUploadService uploadService = registry.UploadService;
            var directoryPath = new DirectoryInfoWrap(Server.MapPath("~/Uploads/Narratives"));
            var narPath = new DirectoryInfoWrap(directoryPath + @"\new\" + file.FileName);
            string path = null;
            string error = null;

            try
            {

YouDeliberate/Views/Admin/Comments.cshtml
@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<div class="comments"></div>
<div class="loader" style="margin-top:10px;"></div>
<div class="pages" style="margin-top:10px;display:none;"></div>

    <script type="text/javascript">

    $(document).ready(function () {
        getNrComments();
        loadBar();
        pageOnClick(1);
    });

    function parseComments(c,start,end) {
        var s = "<table id='list'><tbody><tr><th>commentID</th><th>Date</th><th>Flag</th><th>Content</th><th>Delete</th></tr>";
        var inr = 1;
        for (var i = start ; i < end; i += 4) {
            if (typeof c[i + 2] != 'undefined')
            {
                if (inr % 2 == 0) {
                    s += "<tr id='comment-" + c[i + 2] + "'>";
                }
                else {
                    s += "<tr id='comment-" + c[i + 2] + "' class='alt'>";
                }
                s += "<th>" + c[i + 2] + "</th>"
                  + "<th>" + c[i + 3] + "</th>"
                  + "<th>False</th>"
                  + "<th>" + c[i + 1] + "</th>"
                  + "<th><a href='#' class='btnwide' onClick=\"delComment('" + c[i + 2] + "')\">Delete</a></th>"
                  + "</tr>";
            }
        }
        s += "</tbody></table>";
        $(".comments").html(s);
        pagesShow();
        loaderHide();
    }

    function delComment(id) {
        $.ajax({
            url: "/Admin/DelComment",
            type: "get",
            data: { id: id },
            success: function (response, textStatus, jqXHR) {
                valid(true, "Comment has been succesfully deleted!");
                var adminTr = "#comment-" + id;
                $(adminTr).remove();
                getNrComments();
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //alert("err");
            },
            // callback handler
            complete: function () {
            }
        });
    }

    function getNrComments() {
        $.ajax({
            url: "/Admin/GetNrComments",
            type: "get",
            success: function (response, textStatus, jqXHR) {
                pages(response);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //alert("err");
            },
            // callback handler
            complete: function () {
            }
        });
    }

    function pages(nr)
    {
        var total = Math.ceil(nr / 25);
        var s = "<table id='list'><tbody><tr>";
        for(var i=1;i<total;i++)
        {
            s += "<th><a class='pageNr-"+i+"' style='color:white' href='#' onclick='pageOnClick("+i+");'>" + i + "</a></th>";
        }
        s += "</tr></tbody></table>"
        $(".pages").html(s);
    }

    function loadBar()
    {
        var s = "<table id='list' border='0' style='background-color:white;border:0;'><tbody><tr>"
             + "<th style='background-color:white;border:0;'><img src='../../Images/progress_bar.gif' /></th>"
             + "</tr></tbody></table>";
        $(".loader").html(s);
    }
    
    function loaderHide()
    {
        $(".loader").css({ display: "none" });
    }

    function pagesShow()
    {
        $(".comments").css({ display: "block" });
        $(".loader").css({ display: "none" });
        $(".pages").css({ display: "block" });
    }

    function pagesHide()
    {
        $(".comments").css({ display: "none" });
        $(".loader").css({ display: "block" });
        $(".pages").css({ display: "none" });
    }

    function pageOnClick(nr)
    {
        var classId = ".pageNr-" + nr;
        $(".pages a").css({ color: "#e1e1e1" });
        $(classId).css({ color: "#7e7e7e" });
        pagesHide();
        load((nr * 25),(nr * 25 + 25));
    }

    function load(start,end) {
        $.ajax({
            url: "/Admin/GetComments",
            type: "get",
            data: { start: start, end: end },
            success: function (response, textStatus, jqXHR) {
                if (response.length = (4 * 25))
                {
                    parseComments(response, 0, (4 * 25));
                } else {
                    parseComments(response, 0, response.length);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //alert("err");
            },
            // callback handler
            complete: function () {
            }
        });
    }
    </script>

YouDeliberate/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<script>
    $(function () {
        $("#UserName").focus();
    });
</script>


@using (Html.BeginForm("Login", "Admin"))
{
    <div class="RenderBody" align="center">
        <form action="POST">
            <p align="center"> Username: <input type="text" name="user" id="UserName" /></p>
            <p align="center"> Password: <input type="password" name="password" id="Password" /></p>
            <p align="center"><input type="submit" value="Login" /></p>
        </form>
    </div>
}

YouDeliberate/Views/Admin/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Admin/_Layout.cshtml";
}
@model IEnumerable<YouDeliberate.Models.Entity.narrative>

<div style="text-align: center;" id="admin_list_nav">Show: <a href="/Admin/List">All</a> - <a href="/Admin/List?f=flagged">Flagged</a> - <a href="/Admin/List?f=nc">Not Categorized</a></div>

<table class="list">
    <tbody>
        <tr>
            <th>ID</th>
            <th style="width:10px;">Published</th>
            <th><i class="fa fa-flag"></i></th>
            <th>Lang.</th>
            <th>Category</th>
            <th><i class="fa fa-smile-o"></i></th>
            <th><i class="fa fa-meh-o"></i></th>
            <th><i class="fa fa-frown-o"></i></th>
            <th><i class="fa fa-eye"></i></th>
            <th><i class="fa fa-comment"></i></th>
        </tr>
    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr @(i % 2 == 0 ? "class=alt" : "") >
            <th><a onclick="populatePopup(@Model.ElementAt(i).narrativeID)" id="grid@(i)" class="fancybox" rel="group" href="#player-pop">@Model.ElementAt(i).narrativeID <i class="fa fa-play"></i></a></th>
            <th>
            @using (Html.BeginForm("SetViewable", "Admin", FormMethod.Post))
            {
                <input onchange='this.form.submit();' type="checkbox" name="form" @(Model.ElementAt(i).userViewable ? "checked" : "") />
                <input type="hidden" name="id" value="@Model.ElementAt(i).narrativeID" />
            }
            </th>
            <th>

            @if (Model.ElementAt(i).narrativeflags.Count > 0)
            {
                <a onclick="getFlags(@Model.ElementAt(i).narrativeID)" id="grid@(i)" class="fancybox" rel="group" href="#flags-pop">@Model.ElementAt(i).narrativeflags.Count </a>
            } else
            {
                <text>0</text>
            }
            </th>
            
            <th><img src="~/Images/lang/@(Model.ElementAt(i).languageID == 1 ? "en" : "fr").png" /> </th>
            <th @(Model.ElementAt(i).categoryID == 4 ? "class=warn" : "")>
                @using (Html.BeginForm("SetCategory", "Admin", FormMethod.Post))
                {
                    <select name="form" onchange="this.form.submit()">
                        <option value="1" @(Model.ElementAt(i).categoryID == 1 ? "selected" : "")>Agree</option>
                        <option value="3" @(Model.ElementAt(i).categoryID == 3 ? "selected" : "")>Ambivalent</option>
                        <option value="2" @(Model.ElementAt(i).categoryID == 2 ? "selected" : "")>Disagree</option>
                        <option value="4" @(Model.ElementAt(i).categoryID == 4 ? "selected" : "")>None</option>
                    </select>
                    <input type="hidden" name="id" value="@Model.ElementAt(i).narrativeID" />
                }
            </th>
            <th>@Model.ElementAt(i).numberAgrees</th>
            <th>@Model.ElementAt(i).numberAmbivalent</th>
            <th>@Model.ElementAt(i).numberDisagrees</th>
            <th>@Model.ElementAt(i).numberViews</th>
            <th>@Model.ElementAt(i).comments.Count</th>
        </tr>
    }
    </tbody>
</table>

<div id="player-pop" style="display: none; height: 600px; width: 320px; overflow:hidden;">
    <div id="popup-close" style="position:absolute; top: 0px;"></div>

    @RenderPage("~/Views/Shared/_Player.cshtml")

</div>

<div id="flags-pop" style="display: none; /*height: auto;*/ width: 320px;">
    <div id="popup-close" style="position:absolute; top: 0px;"></div>
        <div id="flags-header"></div>
        <table class="list" style="width:320px;">
            <tbody id ="flags-list" style="text-align: left;">
            </tbody>
        </table>
</div>

<script>
    function getFlags(id) {
        $.ajax({
            url: "/Admin/GetFlags",
            type: "get",
            data: { id: id },
            success: function (response, textStatus, jqXHR) {
                //console.log(response);
                parseFlags(response, id);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //alert("err");
            },
            // callback handler
            complete: function () {
            }
        });
    }

    function parseFlags(c, id) {
        $("#flags-header").html("Flags for narrative: " + id);
        var s = "";
        var a = "";
        for (var i = 0; i < c.length; i++) {
            if (i % 2 == 0) {
                a = "<tr class='alt' ><th style='width:20px'>" + (i+1) + "</th><th>" + c[i] + "</th></tr>"
            } else {
                a = "<tr><th style='width:20px'>" + (i+1) + "</th><th>" + c[i] + "</th></tr>"
            }

            s += a;
        }
        $("#flags-list").html(s);
    }
</script>

YouDeliberate/Views/Admin/Metrics.cshtml
@{
    ViewBag.Title = "Metrics";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<div class="sixteen columns" style="background: #7e7e7e; color: white; text-align: center; margin-bottom: 20px; ">
    <a href="https://www.google.com/analytics/web/?et=&authuser=#report/visitors-overview/a47536103w78815904p81501304/"> <font color="fbfbfb">Go to Google Analytics Dashboard</font></a>
</div>

<div class="eight columns metrics-grid">
    <div class="metrics-header">
        Overall Statistics
    </div>
    <div class="metrics-stat">
        Narrative views: @ViewData["views"] <br />
        Comments: @ViewData["comments"] <br />
        Flagged narratives: @ViewData["flagged"] <br />
    </div>
</div>

<div class="clear"></div>

<!--<a href="#" onclick="_gaq.push(['_trackEvent', 'Videos', 'Play', 'TEST']);">Play</a>-->


<!--<button type="button" onclick="_gaq.push(['_trackEvent', 'Buttons', 'ClickMe', 'TEST']);">Click Me!</button>-->
<br />
@ViewBag.Done

<input type="button" value="Write to Excel" onclick="location.href='@Url.Action("WriteToCsv", "Admin")'" />

YouDeliberate/Views/Admin/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<div id="upload-container" class="sixteen columns">
    <div id="upload">Choose a .zip file to upload...</div>
</div>

<script>
    $(document).ready(function () {
        var u = $("#upload").uploadFile({
            url: "/Admin/Upload",
            allowedTypes: "zip",
            multiple: false,
            maxFileCount: 1,
            autoSubmit: true,
            error: function (x, e) {
                $('.ajax-file-upload-filename').html("There was a problem uploading your file. Please try again.");
            },
            onSuccess: function (files, data, xhr) {
                    $('.ajax-file-upload-filename').html('Your file was uploaded successfully! Redirecting you in 3 seconds...');
                    setTimeout(function () {
                        window.location.href = "/Admin/List";
                    }, 3000);
               }
            });
    });
</script>

YouDeliberate/Views/Admin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/admin.css">

    @Scripts.Render("~/bundles/analytics")

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.uploadfile.js"></script>

    <link rel="stylesheet" href="~/Content/jquery.uploadfile.css">
</head>
<body>
    <div class="container">
        <div class="sixteen columns" style="margin-top:20px;">
            <img src="~/Images/logo.png" alt="YouDeliberate" style="float:right;" />
        </div>
        <div class="sixteen columns menu-top">
            @if (@Session["admin"] != null)
            {
                <ul class="buttons">
                    <li style="margin-left: 5px;">Narrative: </li>
                    <li><a href="/Admin/Upload">Add</a></li>
                    <li><a href="/Admin/List">List</a></li>
                    <li><a href="/Admin/Comments">Comments</a></li>
                    <li style="margin-left: 5px;">Misc: </li>
                    <li><a href="/Admin/Metrics">Metrics</a></li>
                    <li><a href="/Admin/Config">Config</a></li>
                    
                    <li style="float:right"><a href="/Admin/Logout">Logout</a></li>
                    <li style="float:right">Welcome, @Session["admin"]!</li>
                </ul>
            }
        </div>
        <div class="successMessage" style="display: none; background-color: green;height:25px;color:green;"></div>
        <div class="errorMessage" style="display: none; background-color: red;height:25px;color:red;"></div>
        <div class="sixteen columns" style="margin: 50px 0 50px 0;">
            @RenderBody()
        </div>
        <div id="footer" class="sixteen columns"></div>
    </div>

    <script>
        function valid(flag, msg) {
            if (flag == true)
            {
                $(".successMessage").css({ "display": "block" });
                $(".errorMessage").css({ "display": "none" });
                $(".successMessage").html(msg);
                setTimeout(function () {
                    $(".successMessage").css({ "display": "none" });
                    $(".errorMessage").css({ "display": "none" });
                    $(".successMessage").html("");
                }, 3000);
            }
            else
            {
                $(".errorMessage").css({ "display": "block" });
                $(".successMessage").css({ "display": "none" });
                $(".errorMessage").html(msg);
                setTimeout(function () {
                    $(".errorMessage").css({ "display": "none" });
                    $(".successMessage").css({ "display": "none" });
                    $(".errorMessage").html("");
                }, 3500);
            }
            
        }
    </script>

</body>
</html>