YouDeliberate/Controllers/BrowseController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web;
using System.Net.Http;
using YouDeliberate.Models.DAO;
using YouDeliberate.Models.Entity;
using YouDeliberate.Models.Services;

using System.Web.Script.Serialization;
using System;

namespace YouDeliberate.Controllers
{
    public class BrowseController : Controller
    {
        private INarrativeService dataService;

        public BrowseController(INarrativeService dataService)
        {
            this.dataService = dataService;
        }

        public ActionResult Index()
        {
            List<narrative> l;
            l = dataService.GetNarratives(viewable: true);
            return View("Index", l);
        }

        [HttpGet]
        public ActionResult SearchList(int id)
        {
            List<Media> l = null;
            try
            {
                l = dataService.GetSearchList(id);
                if (l == null)
                {
                    throw new NullReferenceException();
                }
            }
            catch (NullReferenceException)
            {
                return new HttpStatusCodeResult(550);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPlaylist(int id)
        {
            List<Media> l = null;
            List<string> returnme = null;
            try
            {

                l = dataService.GetPlayList(id);
                returnme = new List<string>();
                if (l == null)
                    throw new NullReferenceException();

                foreach (var item in l)
                {
                    returnme.Add(item.Audio.path + "");
                    returnme.Add(item.Picture.path + "");
                }

            }
            catch (NullReferenceException)
            {
                return new HttpStatusCodeResult(550);
            }

            return Json(returnme, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SortViewNarratives(string sortType, string langType, string filtType)
        {
            List<narrative> l;
            if (!String.IsNullOrEmpty(filtType))
            {
                ViewBag.PreviousFilterType = filtType;
            }
            if (!String.IsNullOrEmpty(langType))
            {
                ViewBag.PreviousLangType = langType;
            }

            l = dataService.GetNarratives(viewable : true); 

            if (!String.IsNullOrEmpty(sortType))
            {
                ViewBag.PreviousSortType = sortType;
                l = dataService.SortNarratives(l, sortType);
            }
            return View("Index", l);
        }
    }
}

YouDeliberate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YouDeliberate.Models.Services;

namespace YouDeliberate.Controllers
{
    public class HomeController : Controller
    {
        ITopicService ts;

        public HomeController()
        {
            ts = new TopicService();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetTopic()
        {
            List<string> topList = ts.GetCurrentTopic();
            return Json(topList, JsonRequestBehavior.AllowGet);
        }
    }
}

YouDeliberate/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<html lang="en">

    <head>
        @Scripts.Render("~/bundles/jquery")
        @Styles.Render("~/Content/css")
        <title>@ViewBag.Title</title>
    </head>

<body>
    <div id="homeMainContent">

        <div class="topic"></div>
        <div class="topic-content" style="position:relative; height:450px"></div>
        <div class="sub-topic"></div>
        <a class="skipButton" href="@Url.Action("Index", "Browse")">Skip to Main Page</a>
    </div>
</body>

</html>

<script type="text/javascript">

    $(document).ready(function () {
        load();
    });

    function load()
    {
        $.ajax({
            url: "/Home/GetTopic",
            type: "get",
            success: function (response, textStatus, jqXHR) {
                includeBody(response);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //alert("err");
            },
            // callback handler
            complete: function () {
            }
        });
    }

    function includeBody(r)
    {
        //r[0] - ("topic");
        //r[1] - ("subtopic");
        //r[2] - ("bg-pic");
        //r[3] - ("en-path");
        //r[4] - ("fr-path");

        var topicContent = "<h1>"+r[0]+"</h1>";
        var subContent = "<h3 style='position:absolute; margin-right: 30px; bottom: 30px; right: 20px'>" + r[1] + "</h3>";
        var bgPic = "url("+r[2]+")";

        $('#homeMainContent').css("background-image", bgPic);

        var enVideo = r[3];
        var frVideo = r[4];

        var videoLayout = "<img src='../Topics/Shared/VideoLayout.png' style='position:absolute; top:50%; left: 50%; margin-left: -555px; margin-top: -250px; width:1000px; height:450px' />"
                     + "<button id='englishBtn' onclick=\"selectEnglish('" + enVideo + "');\" style='position: absolute; top: 25%; left: 50%; margin-top: 25px; margin-left: 300px;'><img src='../../Images/lang/en.png'></button>"
                     + "<button id='frenchBtn' onclick=\"selectFrench('" + frVideo + "');\" style='position: absolute; top: 25%; left: 50%; margin-top: 25px; margin-left: 340px;'><img src='../../Images/lang/fr.png'></button>"
                     + "<video id='video' width='400' height='300'>"
                     + "<source src='" + enVideo + "' id='videoLang' type='video/mp4'>"
                     + "</video>"
                     + "<button id='playBtn' class='homePlayButton' onclick='playPause()'><img src='../Topics/Shared/ButtonPlay.png'></button>";

        $('.topic').html(topicContent);
        $('.sub-topic').html(subContent);
        $('.topic-content').html(videoLayout);
    }

    var vidPlayed = false;

    introVideo.onended = function () {
        vidPlayed = false;
        $("#playBtn").children().attr("src", "../../Topics/Shared/ButtonPlay.png");
    }

    function playPause(video) {
        var introVideo = document.getElementById('video');
        if (introVideo.paused){
            introVideo.play();
            $("#playBtn").children().attr("src", "../../Topics/Shared/ButtonPause.png");
            vidPlayed = true;
        }            
        else {
            introVideo.pause();
            $("#playBtn").children().attr("src", "../../Topics/Shared/ButtonPlay.png");
        }        
    }

    function selectEnglish(enPath) {
        $("#video").find("#videoLang").attr("src", enPath);
        $("#playBtn").children().attr("src", "../../Topics/Shared/ButtonPlay.png");
        $("#video").load();
    }

    function selectFrench(frPath) {
        $("#video").find("#videoLang").attr("src", frPath);
        $("#playBtn").children().attr("src", "../../Topics/Shared/ButtonPlay.png");
        $("#video").load();
    }

</script>